import XCTest
@testable import SwiftBaoCodegen

final class SwiftEmitterTests: XCTestCase {

    private func emit(_ toml: String, opts: EmitOptions = EmitOptions()) throws -> [String: String] {
        let schemas = try TomlParser.parse(tomlString: toml, swiftNameSuffix: "Record")
        let emitter = SwiftEmitter(options: opts)
        var out: [String: String] = [:]
        for s in schemas {
            out[s.swiftName] = emitter.emit(schema: s)
        }
        return out
    }

    func testGeneratedStructConformsToEquatableHashableCodable() throws {
        // A2 — codegen emits `Equatable, Hashable, Codable` on the
        // struct itself so the compiler's same-file synthesis fires.
        // This obsoletes the ~80 lines of hand-rolled boilerplate
        // users used to need per model. Pin the contract.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(
            body.contains("struct TRecord: PrimitiveModel, PrimitiveRowDecodable, Equatable, Hashable, Codable"),
            "generated struct should conform to PrimitiveModel + row decoding + Equatable, Hashable, Codable"
        )
    }

    func testEmitsHeader() throws {
        let src = try emit("[models.x]\n[models.x.fields.id]\ntype = \"id\"")
        let body = try XCTUnwrap(src["XRecord"])
        XCTAssertTrue(body.contains("// Generated by swift-bao-codegen — DO NOT EDIT."))
        XCTAssertTrue(body.contains("import JsBaoClient"))
    }

    func testEmitsAppFacingModelFacade() throws {
        // The one-model `Model.*` facade (#918) is the SINGLE app-facing API
        // for a generated model — cross-document reads + per-document
        // instance writes (`save(in:)` / `delete(in:)`, the JS `save()`
        // shape). It once silently vanished when an unrelated emitter
        // refactor dropped `crossDocumentFacade` (regression on
        // js-parity-jun-3); nothing caught it because the only facade test
        // hand-writes its own copy of the extension. Pin every member so a
        // future emitter change can't drop it without a red test.
        let src = try emit("""
        [models.note]
        [models.note.fields.id]
        type = "id"
        [models.note.fields.title]
        type = "string"
        required = true
        """)
        let body = try XCTUnwrap(src["NoteRecord"])
        XCTAssertTrue(body.contains("extension NoteRecord {"),
                      "facade extension should be emitted")
        // Reads (cross-document statics)
        XCTAssertTrue(body.contains("static func query(_ filter: DocumentFilter? = nil, options: QueryOptions? = nil) throws -> [NoteRecord]"),
                      "query facade must throw (substring-op input errors surface, #1119)")
        XCTAssertTrue(body.contains("static func query(_ filter: DocumentFilter? = nil, options: QueryOptions? = nil, include: [Include]) throws -> [NoteRecord]"),
                      "query-time include facade must be emitted")
        XCTAssertTrue(body.contains(".queryShared(primitiveSchema, filter: filter, options: options, include: include)"),
                      "include query should delegate to the shared include engine")
        // Paginated read — exposes nextCursor/hasMore so callers can page (#946).
        XCTAssertTrue(body.contains("static func queryPaged(_ filter: DocumentFilter? = nil, options: QueryOptions? = nil) throws -> PagedQueryResult<NoteRecord>"))
        XCTAssertTrue(body.contains("static func queryPaged(_ filter: DocumentFilter? = nil, options: QueryOptions? = nil, include: [Include]) throws -> PagedQueryResult<NoteRecord>"),
                      "paginated include facade must be emitted")
        XCTAssertTrue(body.contains("static func count(_ filter: DocumentFilter? = nil) throws -> Int"))
        // find/findAll are synchronous throws + decode-loud (#1156): all facade
        // reads share one sync convention (the shared store never suspends), and
        // a row that exists but fails typed decode still throws
        // PrimitiveDecodeError instead of vanishing (find) or being silently
        // dropped from the result (findAll).
        XCTAssertTrue(body.contains("static func findAll() throws -> [NoteRecord]"))
        XCTAssertFalse(body.contains("static func findAll() async throws"),
                       "findAll must be synchronous throws, not async (#1156)")
        XCTAssertTrue(body.contains("static func find(_ id: String) throws -> NoteRecord?"))
        XCTAssertFalse(body.contains("static func find(_ id: String) async throws"),
                       "find must be synchronous throws, not async (#1156)")
        XCTAssertTrue(body.contains("throw PrimitiveDecodeError(modelName: modelName, row: row)"),
                      "decode misses in find/findAll must throw, not return nil / drop rows")
        XCTAssertTrue(body.contains("static func subscribe(_ callback: @escaping @Sendable () -> Void) -> @Sendable () -> Void"))
        XCTAssertTrue(body.contains("static func aggregate(_ options: AggregateOptions) throws -> [[String: Any]]"))
        // Cross-document unique lookup + single-result query (JS parity:
        // findByUnique / queryOne).
        XCTAssertTrue(body.contains("static func findByUnique(_ constraint: String, _ value: PrimitiveValue) throws -> NoteRecord?"),
                      "findByUnique facade must be emitted")
        XCTAssertTrue(body.contains("findByUniqueShared(primitiveSchema, constraint: constraint, value: value)"),
                      "findByUnique should delegate to findByUniqueShared")
        XCTAssertTrue(body.contains("static func queryOne(_ filter: DocumentFilter? = nil, options: QueryOptions? = nil) throws -> NoteRecord?"),
                      "queryOne facade must be emitted")
        XCTAssertTrue(body.contains("queryOneShared(primitiveSchema, filter: filter, options: options)"),
                      "queryOne should delegate to queryOneShared")
        // queryOne with query-time relationship includes (#1216) — the typed
        // parity hole left after #1194 added include only to query/queryPaged.
        XCTAssertTrue(body.contains("static func queryOne(_ filter: DocumentFilter? = nil, options: QueryOptions? = nil, include: [Include]) throws -> NoteRecord?"),
                      "queryOne include overload must be emitted")
        XCTAssertTrue(body.contains("queryOneShared(primitiveSchema, filter: filter, options: options, include: include)"),
                      "queryOne include overload should delegate to queryOneShared(...,include:)")
        // Writes (per-document instance methods — the save() API from #923)
        XCTAssertTrue(body.contains("func save(in documentId: String) throws -> NoteRecord"),
                      "instance save(in:) (create-or-update) must be emitted")
        // Upsert-by-unique-field write (JS parity: save({ upsertOn })).
        XCTAssertTrue(body.contains("func save(in documentId: String, upsertOn: String) throws -> NoteRecord"),
                      "instance save(in:upsertOn:) must be emitted")
        XCTAssertTrue(body.contains("upsertShared(Self.primitiveSchema, id: id, values: primitiveValues(), on: upsertOn, in: documentId, explicitId: _explicitId)"),
                      "save(in:upsertOn:) should delegate to upsertShared, passing the record id + explicit-id provenance (#1122)")
        // The upsert paths must return the RESOLVED record, not `self` —
        // on the merge path the existing record's id wins (JS reassigns
        // `this.id = existingId`), so the facade re-decodes the result.
        XCTAssertTrue(body.contains("if let resolved = NoteRecord(record: result.record) { return resolved }"),
                      "upsert facades should re-decode the resolved record so merge keeps the existing id")
        XCTAssertFalse(body.contains("on: upsertOn, in: documentId)\n        return self"),
                      "save(in:upsertOn:) must not return stale `self` (its id is wrong on the merge path)")
        // Upsert-by-named-constraint write (JS parity: Model.upsertByUnique,
        // covers compound constraints — #1053).
        XCTAssertTrue(body.contains("func upsertByUnique(_ constraint: String, mode: UpsertMode = .either, in documentId: String) throws -> NoteRecord"),
                      "instance upsertByUnique(_:mode:in:) must be emitted")
        XCTAssertTrue(body.contains("upsertByUniqueShared(Self.primitiveSchema, id: id, values: primitiveValues(), constraint: constraint, mode: mode, in: documentId, explicitId: _explicitId)"),
                      "upsertByUnique should delegate to upsertByUniqueShared, passing the record id + explicit-id provenance (#1122)")
        // Explicit lookup-value overload (#1122 — js-bao's separate
        // `uniqueLookupValue` argument).
        XCTAssertTrue(body.contains("func upsertByUnique(_ constraint: String, lookupValue: [PrimitiveValue], mode: UpsertMode = .either, in documentId: String) throws -> NoteRecord"),
                      "instance upsertByUnique(_:lookupValue:mode:in:) overload must be emitted")
        XCTAssertTrue(body.contains("uniqueLookupValue: lookupValue"),
                      "lookup-value overload should forward uniqueLookupValue")
        // Explicit-id provenance (#1122): the auto-id convenience init
        // marks the id non-explicit so a colliding auto-id silently
        // merges; the designated init leaves the default `true`.
        XCTAssertTrue(body.contains("var _explicitId: Bool = true"),
                      "explicit-id provenance flag must be emitted")
        XCTAssertTrue(body.contains("var related: RelatedRecords = .empty"),
                      "query-time include payload bag must be emitted")
        XCTAssertTrue(body.contains("self.related = RelatedRecords(raw: row[\"_related\"] as? [String: Any] ?? [:])"),
                      "row init must preserve `_related` include payloads")
        XCTAssertTrue(body.contains("self.id = PrimitiveSchemaRegistry.newId()"),
                      "auto-id convenience init must be emitted")
        XCTAssertTrue(body.contains("self._explicitId = false"),
                      "auto-id init must mark the id non-explicit")
        XCTAssertTrue(body.contains("func delete(in documentId: String) throws"),
                      "instance delete(in:) must be emitted")
        // The deleted static create/update writes must NOT come back.
        XCTAssertFalse(body.contains("static func create("),
                       "static create() was replaced by instance save(in:) (#923)")
        XCTAssertFalse(body.contains("static func update("),
                       "static update() was replaced by instance save(in:) (#923)")
    }

    func testEmitsEnumAccessorForKeywordNamedField() throws {
        // Regression: a string field named after a Swift keyword (e.g.
        // `default`) with an `enum = [...]` once emitted `` `default`Enum ``
        // — the backtick wrapped only the keyword, so the accessor name was a
        // syntax error. The composed identifier must be escaped as a whole
        // (`defaultEnum` isn't a keyword, so it stays clean).
        let src = try emit("""
        [models.widget]
        [models.widget.fields.id]
        type = "id"
        [models.widget.fields.default]
        type = "string"
        enum = ["on", "off"]
        """)
        let body = try XCTUnwrap(src["WidgetRecord"])
        // The typed accessor compiles: composed-then-escaped, no stray backtick.
        XCTAssertTrue(body.contains("var defaultEnum: DefaultValue?"),
                      "enum accessor for keyword field should be `defaultEnum`, not broken backticks")
        XCTAssertFalse(body.contains("`default`Enum"),
                       "must not emit a backtick wrapping only the keyword")
        // The stored property reference inside the accessor still escapes the
        // keyword correctly (`\\`default\\``).
        XCTAssertTrue(body.contains("`default`.flatMap(DefaultValue.init(rawValue:))"))
    }

    func testCustomModuleImport() throws {
        let opts = EmitOptions(accessLevel: "internal", moduleImport: "MyCore", sourcePath: "schema.toml")
        let src = try emit("[models.x]\n[models.x.fields.id]\ntype = \"id\"", opts: opts)
        XCTAssertTrue(try XCTUnwrap(src["XRecord"]).contains("import MyCore"))
    }

    func testPublicAccessPropagatesEverywhere() throws {
        let opts = EmitOptions(accessLevel: "public", moduleImport: "JsBaoClient", sourcePath: "")
        let src = try emit("""
        [models.tasks]
        [models.tasks.fields.id]
        type = "id"
        [models.tasks.fields.title]
        type = "string"
        required = true
        """, opts: opts)
        let body = try XCTUnwrap(src["TasksRecord"])
        XCTAssertTrue(body.contains("public struct TasksRecord"))
        XCTAssertTrue(body.contains("public static let modelName"))
        XCTAssertTrue(body.contains("public var id: String"))
        XCTAssertTrue(body.contains("public init?(record:"))
        XCTAssertTrue(body.contains("public func primitiveValues"))
    }

    func testDefaultAccessIsPublic() throws {
        // The default access modifier emitted by codegen must be
        // `public` — app code typically adds a companion extension
        // (`public extension TodoItem { init(text: String) { ... } }`),
        // which the compiler rejects on internal types ("public
        // modifier cannot be used in extensions that declare members
        // on an internal type"). Pin the default so future refactors
        // can't silently regress.
        let src = try emit("""
        [models.tasks]
        [models.tasks.fields.id]
        type = "id"
        """)
        let body = try XCTUnwrap(src["TasksRecord"])
        XCTAssertTrue(body.contains("public struct TasksRecord"),
                      "default emitter access should be `public`")
        XCTAssertTrue(body.contains("public var id: String"))
        XCTAssertTrue(body.contains("public init("))
    }

    func testPrimitiveValuesUsesLetWhenNoOptionalFields() throws {
        // No optional fields → `values` is never mutated, so the
        // emitter must use `let` to avoid the per-build
        // "variable 'values' was never mutated" warning.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("let values: [String: PrimitiveValue] = ["),
                      "expected `let values` when no optional fields are present")
        XCTAssertFalse(body.contains("var values: [String: PrimitiveValue]"),
                       "should not emit `var values` when nothing mutates it")
    }

    func testPrimitiveValuesUsesVarWhenOptionalFieldsPresent() throws {
        // Optional fields → `values` is conditionally extended via
        // `values["x"] = ...`, so `var` is required.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        [models.t.fields.note]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var values: [String: PrimitiveValue]"),
                      "expected `var values` when there's at least one optional field")
    }

    func testBooleanRowReadUsesNonTrailingClosure() throws {
        // `(row[..] as? Int).map { ... }` triggers the "trailing
        // closure in this context is confusable with the body of the
        // statement" warning when it sits inside a `guard let ... else
        // { return nil }` chain. The emitter must use the
        // non-trailing form `.map({ ... })`.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.done]
        type = "boolean"
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains(".map({ $0 != 0 })"),
                      "boolean row-read should use non-trailing closure")
        XCTAssertFalse(body.contains(".map { $0 != 0 }"),
                       "no trailing-closure form for boolean row-read")
    }

    func testInitParameterOrderMatchesSchemaDeclarationOrder() throws {
        // The parser recovers field declaration order from the TOML
        // source — a schema written `zzz, id, aaa` emits an init in
        // that *same* order, not alphabetical (which would silently
        // re-shuffle a caller's positional args). The runtime never
        // depends on init parameter order, so source-order is purely
        // a developer-ergonomics fix.
        let src = try emit("""
        [models.tasks]
        [models.tasks.fields.zzz]
        type = "string"
        [models.tasks.fields.id]
        type = "id"
        [models.tasks.fields.aaa]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TasksRecord"])
        guard let initRange = body.range(of: "init(\n") else {
            return XCTFail("no init found")
        }
        let initBody = body[initRange.upperBound...]
        let paramLines = initBody.split(separator: "\n").prefix(3).map(String.init)
        XCTAssertTrue(paramLines[0].contains("zzz:"),
                      "expected zzz first, got: \(paramLines[0])")
        XCTAssertTrue(paramLines[1].contains("id:"),
                      "expected id second, got: \(paramLines[1])")
        XCTAssertTrue(paramLines[2].contains("aaa:"),
                      "expected aaa third, got: \(paramLines[2])")
    }

    func testRequiredFieldGuardsInRecordInit() throws {
        let src = try emit("""
        [models.tasks]
        [models.tasks.fields.id]
        type = "id"
        [models.tasks.fields.title]
        type = "string"
        required = true
        [models.tasks.fields.note]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TasksRecord"])
        XCTAssertTrue(body.contains(#"guard let title = record["title"]?.asString"#))
        // Optional `note` should NOT be in the guard.
        XCTAssertFalse(body.contains(#"let note = record["note"]"#))
        XCTAssertTrue(body.contains(#"self.note = record["note"]?.asString"#))
    }

    func testAllOptionalFieldsOmitsGuardInRecordInit() throws {
        let src = try emit("""
        [models.x]
        [models.x.fields.id]
        type = "id"
        [models.x.fields.counter]
        type = "number"
        """)
        let body = try XCTUnwrap(src["XRecord"])
        // Locate just the record-init body. init?(row:) always guards
        // on `id` from the row dict, so we can't check the whole file.
        guard let recordInitStart = body.range(of: "init?(record: PrimitiveRecord)") else {
            return XCTFail("no record init found")
        }
        guard let rowInitStart = body.range(of: "init?(row:") else {
            return XCTFail("no row init found")
        }
        let recordInitBody = body[recordInitStart.upperBound..<rowInitStart.lowerBound]
        XCTAssertFalse(
            recordInitBody.contains("guard"),
            "init?(record:) should not have a guard when no fields are required:\n\(recordInitBody)"
        )
    }

    func testFieldTypeMappings() throws {
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.s]
        type = "string"
        [models.t.fields.n]
        type = "number"
        [models.t.fields.b]
        type = "boolean"
        [models.t.fields.d]
        type = "date"
        [models.t.fields.tags]
        type = "stringset"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var s: String?"))
        XCTAssertTrue(body.contains("var n: Double?"))
        XCTAssertTrue(body.contains("var b: Bool?"))
        XCTAssertTrue(body.contains("var d: String?"))
        XCTAssertTrue(body.contains("var tags: Set<String>?"))
        // accessors
        XCTAssertTrue(body.contains(".asString"))
        XCTAssertTrue(body.contains(".asNumber"))
        XCTAssertTrue(body.contains(".asBoolean"))
        XCTAssertTrue(body.contains(".asDateString"))
        XCTAssertTrue(body.contains(".asStringSet"))
    }

    func testRequiredFieldIsNonOptional() throws {
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var title: String\n"))
    }

    func testPrimitiveValuesShape() throws {
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        [models.t.fields.note]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        // Required goes in the literal; optional uses `if let`.
        XCTAssertTrue(body.contains(#""title": .string(title)"#))
        XCTAssertTrue(body.contains(#"if let note { values["note"] = .string(note) }"#))
    }

    func testFieldDescriptorIncludesRelevantFlags() throws {
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.email]
        type = "string"
        unique = true
        indexed = true
        max_length = 256
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(
            body.contains(#"FieldDescriptor(type: .string, indexed: true, unique: true, required: true, maxLength: 256)"#),
            body
        )
    }

    func testCustomClassNameOverride() throws {
        let src = try emit("""
        [models.tasks]
        class_name = "TaskRecord"

        [models.tasks.fields.id]
        type = "id"
        """)
        XCTAssertNotNil(src["TaskRecord"])
        XCTAssertNil(src["TasksRecord"])
    }

    func testSwiftKeywordFieldNameIsBacktickEscaped() throws {
        // Swift's `default` is a keyword — emitter must wrap in backticks.
        // This isn't user-friendly, but the alternative (silently renaming)
        // breaks the model name → field key invariant the runtime relies on.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.default]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var `default`: String?"))
    }

    func testEverySwiftKeywordAsFieldName_isBacktickEscapedEverywhere() throws {
        // Sweep every reserved keyword the emitter knows about and
        // verify the generated code escapes it at every Swift-identifier
        // call site:
        //   1. The stored property declaration
        //   2. The designated init parameter
        //   3. The designated init body LHS + RHS
        //   4. The init?(record:) body LHS
        //   5. The init?(row:) body LHS
        //   6. The primitiveValues() body (`if let` shorthand + .string(...) ref)
        //
        // A few keywords would either not parse as a TOML key without
        // quoting (e.g. one with whitespace) or are already exercised
        // elsewhere — skip those. This loop catches the long tail.
        // The wider point is: the emitter routes every field-name use
        // through `propName(...)`; if a future refactor ever bypasses
        // it, this test fails loud across the whole keyword set.
        for keyword in [
            "class", "init", "var", "let", "for", "while", "if", "else",
            "return", "break", "continue", "throw", "try", "catch",
            "switch", "case", "where", "guard", "defer", "do", "in",
            "self", "Self", "Any", "true", "false", "nil", "default",
            "static", "func", "private", "public", "internal", "open",
            "operator", "subscript", "typealias", "rethrows", "throws",
            "protocol", "extension", "struct", "enum", "import",
        ] {
            let toml = """
            [models.t]
            [models.t.fields.id]
            type = "id"
            [models.t.fields.\(keyword)]
            type = "string"
            """
            let src = try emit(toml)
            let body = try XCTUnwrap(src["TRecord"], "no TRecord for keyword '\(keyword)'")

            // Stored property declaration
            XCTAssertTrue(
                body.contains("var `\(keyword)`: String?"),
                "missing stored property backtick escape for '\(keyword)'"
            )
            // Designated init body — `self.\`X\` = \`X\``
            XCTAssertTrue(
                body.contains("self.`\(keyword)` = `\(keyword)`"),
                "missing designated-init body escape for '\(keyword)'"
            )
            // init?(record:) body
            XCTAssertTrue(
                body.contains("self.`\(keyword)` = record[\"\(keyword)\"]?"),
                "missing init?(record:) body escape for '\(keyword)'"
            )
            // init?(row:) body
            XCTAssertTrue(
                body.contains("self.`\(keyword)` = row[\"\(keyword)\"]"),
                "missing init?(row:) body escape for '\(keyword)'"
            )
            // primitiveValues() body — `if let \`X\` { values["X"] = .string(\`X\`) }`
            XCTAssertTrue(
                body.contains("if let `\(keyword)`"),
                "missing primitiveValues() if-let escape for '\(keyword)'"
            )
            XCTAssertTrue(
                body.contains(".string(`\(keyword)`)"),
                "missing primitiveValues() value-ref escape for '\(keyword)'"
            )
        }
    }

    func testFieldNameStartingWithUnderscore_isPreservedAsIs() throws {
        // Field names starting with `_` are RESERVED in convention
        // (`_meta_*`, `_uniqueIdx_*`, `_meta_doc_id`) but the emitter
        // doesn't currently reject them — it just emits them. Test
        // pins that today behavior; if we ever add validation, this
        // should flip to expect a thrown CodegenError.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields._user_meta]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var _user_meta: String?"),
                      "underscore-prefixed field names are emitted as-is today")
    }

    func testUnicodeFieldName_requiresQuotedTomlKey_andEmitsAsIs() throws {
        // TOML spec: bare keys are ASCII `[A-Za-z0-9_-]+` only.
        // Non-ASCII keys MUST be quoted (`"café"`). With quoted keys
        // the field passes through the emitter untouched and lands
        // on the generated struct as a Swift identifier (Swift
        // accepts Unicode L*/Nl chars in identifiers).
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields."café"]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var café: String?"),
                      "unicode field name should emit as-is when TOML key is quoted")
    }

    func testUnicodeModelName_requiresQuotedTomlKey_emitsPascalCased() throws {
        // Same TOML rule — model names with non-ASCII must be quoted
        // in the table header. `Naming.pascalCase` only special-cases
        // `_`/`-`/space as word boundaries, so a unicode model name
        // surfaces with its first character upper-cased and the rest
        // verbatim. Default suffix `Record` appended.
        let src = try emit("""
        [models."café"]
        [models."café".fields.id]
        type = "id"
        """)
        XCTAssertNotNil(src["CaféRecord"],
                        "expected CaféRecord, got keys: \(Array(src.keys))")
    }

    func testUnquotedUnicodeKey_doesNotEmitAModel() throws {
        // TOML spec rejects unquoted non-ASCII bare keys. Two valid
        // outcomes here:
        //   • TOMLKit raises a parse error → `.parse` is thrown.
        //   • TOMLKit truncates `[models.café]` to a bare `[models]`
        //     header with no children → we successfully parse an empty
        //     schema list (since a comment-only / model-less TOML is
        //     valid input for fresh-template onboarding).
        // The user-visible failure mode in the second case is "my
        // generated type is missing", which they'll hit immediately at
        // compile time — quoting the key fixes it.
        do {
            let src = try emit("""
            [models.café]
            [models.café.fields.id]
            type = "id"
            """)
            XCTAssertTrue(src.isEmpty,
                          "expected zero emitted records, got keys: \(Array(src.keys))")
        } catch CodegenError.parse {
            // Acceptable: TOMLKit surfaced a parse error.
        } catch {
            XCTFail("expected CodegenError.parse or empty output, got \(error)")
        }
    }

    // MARK: - Relationship accessors (#995)

    /// Emit every model in `toml`, wiring up the cross-model name map
    /// exactly like the CLI driver does so relationship accessors can name
    /// their typed return types.
    private func emitWithNameMap(
        _ toml: String,
        accessLevel: String = "public"
    ) throws -> (files: [String: String], schemas: [ParsedSchema], emitter: SwiftEmitter) {
        let schemas = try TomlParser.parse(tomlString: toml, swiftNameSuffix: "Record")
        var names: [String: String] = [:]
        for s in schemas { names[s.name] = s.swiftName }
        let emitter = SwiftEmitter(options: EmitOptions(
            accessLevel: accessLevel,
            moduleImport: "JsBaoClient",
            sourcePath: "schema.toml",
            swiftNamesByModel: names
        ))
        var files: [String: String] = [:]
        for s in schemas { files[s.swiftName] = emitter.emit(schema: s) }
        return (files, schemas, emitter)
    }

    private static let relationshipFixture = """
    [models.posts]
    [models.posts.fields.id]
    type = "id"
    [models.posts.fields.userId]
    type = "string"
    [models.posts.relationships.author]
    type = "refersTo"
    model = "users"
    related_id_field = "userId"
    [models.posts.relationships.tags]
    type = "hasManyThrough"
    model = "tags"
    join_model = "post_tag_links"
    join_model_local_field = "postId"
    join_model_related_field = "tagId"

    [models.users]
    [models.users.fields.id]
    type = "id"
    [models.users.relationships.posts]
    type = "hasMany"
    model = "posts"
    related_id_field = "userId"
    order_by_field = "createdAt"

    [models.tags]
    [models.tags.fields.id]
    type = "id"

    [models.post_tag_links]
    [models.post_tag_links.fields.id]
    type = "id"
    """

    // Relationship accessors are idiomatic INSTANCE methods that
    // auto-resolve the target model (#1151) — `try post.author()`,
    // `try user.posts()` — mirroring the JS client's generated
    // instance methods. They delegate to the default client's
    // cross-document relationship helpers. Synchronous throws (#1156):
    // the shared store never suspends.

    func testRefersToAccessorReturnsTypedOptional() throws {
        let (files, _, _) = try emitWithNameMap(Self.relationshipFixture)
        let posts = try XCTUnwrap(files["PostsRecord"])
        XCTAssertTrue(
            posts.contains("func author() throws -> UsersRecord?"),
            "expected an instance accessor returning the target's optional typed record"
        )
        XCTAssertTrue(
            posts.contains(#".refersToShared(target: UsersRecord.primitiveSchema, foreignKey: userId)"#),
            "refersTo accessor should resolve via the default client, reading its own FK field"
        )
        XCTAssertTrue(
            posts.contains("var relatedAuthor: UsersRecord?")
            && posts.contains(#"related.one("author", as: UsersRecord.self)"#)
            && posts.contains("related.one(UsersRecord.modelName, as: UsersRecord.self)"),
            "refersTo should expose a typed query-time include accessor"
        )
        XCTAssertTrue(
            posts.contains("static func includeAuthor(")
            && posts.contains("type: .refersTo")
            && posts.contains(#"sourceField: "userId""#),
            "refersTo should expose a generated query-time include builder"
        )
        XCTAssertFalse(
            posts.contains("static func author("),
            "the refersTo accessor should be an instance method, not a static"
        )
    }

    func testHasManyAccessorReturnsTypedArray() throws {
        let (files, _, _) = try emitWithNameMap(Self.relationshipFixture)
        let users = try XCTUnwrap(files["UsersRecord"])
        XCTAssertTrue(
            users.contains("func posts() throws -> [PostsRecord]"),
            "hasMany accessor should be an instance method returning an array of the target's typed record"
        )
        XCTAssertTrue(
            users.contains(#".hasManyShared("#)
            && users.contains(#"target: PostsRecord.primitiveSchema"#)
            && users.contains(#"relatedIdField: "userId""#)
            && users.contains("sourceId: id"),
            "hasMany accessor should resolve the target via the default client by FK = self.id"
        )
        XCTAssertTrue(
            users.contains(#"orderByField: "createdAt""#),
            "hasMany accessor should forward the declared order_by_field"
        )
        XCTAssertTrue(
            users.contains("var relatedPosts: [PostsRecord]")
            && users.contains(#"related.many("posts", as: PostsRecord.self)"#)
            && users.contains("related.many(PostsRecord.modelName, as: PostsRecord.self)"),
            "hasMany should expose a typed query-time include accessor"
        )
        XCTAssertTrue(
            users.contains("static func includePosts(")
            && users.contains("type: .hasMany")
            && users.contains(#"foreignKey: "userId""#)
            && users.contains(#"sort: [String: Int]? = ["createdAt": 1]"#),
            "hasMany should expose a generated query-time include builder with relationship sort defaults"
        )
    }

    func testHasManyThroughAccessorTakesJoinModel() throws {
        let (files, _, _) = try emitWithNameMap(Self.relationshipFixture)
        let posts = try XCTUnwrap(files["PostsRecord"])
        XCTAssertTrue(
            posts.contains("func tags() throws -> [TagsRecord]"),
            "hasManyThrough accessor should be an instance method returning the target array"
        )
        XCTAssertTrue(
            posts.contains(#".hasManyThroughShared("#)
            && posts.contains(#"target: TagsRecord.primitiveSchema"#)
            && posts.contains(#"joinModel: PostTagLinksRecord.primitiveSchema"#)
            && posts.contains(#"joinModelLocalField: "postId""#)
            && posts.contains(#"joinModelRelatedField: "tagId""#),
            "hasManyThrough accessor should auto-resolve both target and join model"
        )
        XCTAssertTrue(
            posts.contains("var relatedTags: [TagsRecord]")
            && posts.contains(#"related.many("tags", as: TagsRecord.self)"#)
            && posts.contains("related.many(TagsRecord.modelName, as: TagsRecord.self)"),
            "hasManyThrough should expose a typed query-time include accessor"
        )
        XCTAssertFalse(
            posts.contains("static func includeTags("),
            "query-time Include does not currently support hasManyThrough, so codegen must not emit a misleading builder"
        )
    }

    /// The emitter also generates a PAGINATED `hasManyThrough` overload
    /// beside the flat one (#1230, rerouted in #1607): a required `limit:`
    /// (so the bare `tags()` still binds), `afterCursor` / `beforeCursor` /
    /// `direction`, returning `PagedQueryResult<Target>` and delegating to
    /// the runtime helper's paginated overload. Cursors are the engine's
    /// opaque `String` tokens, shared with the JS client's composite cursor.
    func testHasManyThroughAccessorEmitsPaginatedOverload() throws {
        let (files, _, _) = try emitWithNameMap(Self.relationshipFixture)
        let posts = try XCTUnwrap(files["PostsRecord"])
        // The bare overload still generates alongside the paginated one.
        XCTAssertTrue(
            posts.contains("func tags() throws -> [TagsRecord]"),
            "the unpaginated hasManyThrough accessor must still be generated"
        )
        XCTAssertTrue(
            posts.contains("func tags(\n")
            && posts.contains("limit: Int,")
            && posts.contains("afterCursor: String? = nil,")
            && posts.contains("beforeCursor: String? = nil,")
            && posts.contains("direction: CursorDirection = .forward")
            && posts.contains(") throws -> PagedQueryResult<TagsRecord>"),
            "paginated hasManyThrough accessor should take limit/afterCursor/beforeCursor/direction and return PagedQueryResult<Target>"
        )
        XCTAssertTrue(
            posts.contains("limit: limit,")
            && posts.contains("afterCursor: afterCursor,")
            && posts.contains("beforeCursor: beforeCursor,")
            && posts.contains("direction: direction"),
            "paginated accessor should forward its pagination args into hasManyThroughShared"
        )
        XCTAssertTrue(
            posts.contains("nextCursor: page.nextCursor,")
            && posts.contains("prevCursor: page.prevCursor,")
            && posts.contains("hasMore: page.hasMore"),
            "paginated accessor should preserve the runtime helper's cursors"
        )
    }

    /// The order-less fixture declares no join order, so the generated
    /// `hasManyThrough` accessor must NOT forward join-order args.
    func testHasManyThroughAccessorOmitsJoinOrderWhenUndeclared() throws {
        let (files, _, _) = try emitWithNameMap(Self.relationshipFixture)
        let posts = try XCTUnwrap(files["PostsRecord"])
        XCTAssertFalse(
            posts.contains("joinModelOrderByField:"),
            "no declared join order → emitter must omit joinModelOrderByField:"
        )
        XCTAssertFalse(
            posts.contains("joinModelOrderDirection:"),
            "no declared join order → emitter must omit joinModelOrderDirection:"
        )
    }

    /// A `hasManyThrough` with a declared `join_model_order_by_field` /
    /// `join_model_order_direction` must forward those into the generated
    /// accessor's `hasManyThroughShared` call (mirrors how `hasMany`
    /// forwards `order_by_field`). Previously these props were parsed but
    /// dropped (#1201).
    func testHasManyThroughAccessorForwardsDeclaredJoinOrder() throws {
        let fixture = """
        [models.posts]
        [models.posts.fields.id]
        type = "id"
        [models.posts.relationships.tags]
        type = "hasManyThrough"
        model = "tags"
        join_model = "post_tag_links"
        join_model_local_field = "postId"
        join_model_related_field = "tagId"
        join_model_order_by_field = "position"
        join_model_order_direction = "DESC"

        [models.tags]
        [models.tags.fields.id]
        type = "id"

        [models.post_tag_links]
        [models.post_tag_links.fields.id]
        type = "id"
        """
        let (files, _, _) = try emitWithNameMap(fixture)
        let posts = try XCTUnwrap(files["PostsRecord"])
        XCTAssertTrue(
            posts.contains(#"joinModelOrderByField: "position""#),
            "hasManyThrough accessor should forward the declared join_model_order_by_field"
        )
        XCTAssertTrue(
            posts.contains(#"joinModelOrderDirection: "DESC""#),
            "hasManyThrough accessor should forward the declared join_model_order_direction"
        )
    }

    func testNoRelationshipsEmitsNoAccessors() throws {
        let (files, _, _) = try emitWithNameMap("""
        [models.tags]
        [models.tags.fields.id]
        type = "id"
        """)
        let tags = try XCTUnwrap(files["TagsRecord"])
        // Every model emits the cross-document facade statics (`query`/`find`/…),
        // so `static func` alone is no longer a relationship-accessor marker.
        // Relationship accessors are uniquely doc-commented "Follow the … relationship".
        XCTAssertFalse(tags.contains("Follow the"),
                       "a model with no relationships should emit no relationship accessors")
    }

    // MARK: - Registration barrel (#995)

    func testBarrelAggregatesAllModelsInOrder() throws {
        let (_, schemas, emitter) = try emitWithNameMap(Self.relationshipFixture)
        let barrel = emitter.emitBarrel(schemas: schemas)
        XCTAssertTrue(barrel.contains("// Generated by swift-bao-codegen — DO NOT EDIT."))
        XCTAssertTrue(barrel.contains("enum GeneratedModels"))
        XCTAssertTrue(barrel.contains("static let all: [any PrimitiveModel.Type]"))
        XCTAssertTrue(barrel.contains("static func register(on client: JsBaoClient)"))
        XCTAssertTrue(barrel.contains("client.registerModels(all)"))
        // Every model's `.self` should appear.
        for s in schemas {
            XCTAssertTrue(barrel.contains("\(s.swiftName).self,"),
                          "barrel missing \(s.swiftName).self")
        }
    }

    func testBarrelEmittedForEmptySchema() throws {
        let schemas = try TomlParser.parse(tomlString: "# no models\n", swiftNameSuffix: "Record")
        XCTAssertTrue(schemas.isEmpty)
        let emitter = SwiftEmitter(options: EmitOptions())
        let barrel = emitter.emitBarrel(schemas: schemas)
        XCTAssertTrue(barrel.contains("static let all: [any PrimitiveModel.Type] = [\n    ]"),
                      "empty schema should still emit an (empty) barrel array")
    }

    func testBarrelFilenameConstant() {
        XCTAssertEqual(SwiftEmitter.barrelFileName, "GeneratedModels.swift")
    }

    func testBarrelRegisterAssertsModelSetMatchesToml() throws {
        // #mirror JS import-time assertion: register(on:) must fail loud if
        // the generated/registered model set drifts from the TOML model set
        // baked in at codegen time (hand-edit, class_name drift, …).
        let (_, schemas, emitter) = try emitWithNameMap(Self.relationshipFixture)
        let barrel = emitter.emitBarrel(schemas: schemas)
        // The expected TOML model-name set is baked in, in declaration order.
        XCTAssertTrue(barrel.contains("static let modelNames: [String] = ["),
                      "barrel should bake the expected TOML model-name set")
        for s in schemas {
            XCTAssertTrue(barrel.contains("\"\(s.name)\","),
                          "modelNames should include the raw TOML name \(s.name)")
        }
        // register(on:) cross-checks registered names against the baked set.
        XCTAssertTrue(barrel.contains("let registered = all.map { $0.primitiveSchema.name }"))
        XCTAssertTrue(barrel.contains("precondition("),
                      "register(on:) must precondition the sets match")
        XCTAssertTrue(barrel.contains("out of sync with the schema TOML"),
                      "precondition message should explain the drift")
        XCTAssertTrue(barrel.contains("client.registerModels(all)"))
    }

    // MARK: - auto_stamp emit (#1056)

    func testAutoStampRidesInsideFieldDescriptorLiteral() throws {
        // #1056: the auto_stamp policy must land INSIDE the per-field
        // FieldDescriptor literal so the shared runtime write path reads it
        // off `primitiveSchema` and actually stamps on save — not just as
        // advisory metadata.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.createdAt]
        type = "number"
        auto_stamp = "create"
        [models.t.fields.updatedAt]
        type = "number"
        auto_stamp = "update"
        [models.t.fields.touchedAt]
        type = "number"
        auto_stamp = "both"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(
            body.contains("FieldDescriptor(type: .number, autoStamp: .create)"),
            "create stamp should ride inside the FieldDescriptor literal:\n\(body)"
        )
        XCTAssertTrue(body.contains("FieldDescriptor(type: .number, autoStamp: .update)"))
        XCTAssertTrue(body.contains("FieldDescriptor(type: .number, autoStamp: .both)"))
    }

    func testAutoStampAdvisoryStaticMapStillEmitted() throws {
        // The advisory `autoStampFields` static is kept for backward
        // compatibility (app code may read the policy keyed by name).
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.createdAt]
        type = "number"
        auto_stamp = "create"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("static let autoStampFields: [String: String] = ["))
        XCTAssertTrue(body.contains(#""createdAt": "create""#))
    }

    func testNoAutoStampEmitsNeitherSlotNorMap() throws {
        // A schema with no auto_stamp field stays byte-stable: no
        // `autoStamp:` arg in any FieldDescriptor, no advisory map.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertFalse(body.contains("autoStamp:"),
                       "no FieldDescriptor should carry an autoStamp arg")
        XCTAssertFalse(body.contains("autoStampFields"),
                       "advisory map should be omitted when nothing declares auto_stamp")
    }

    // MARK: - enum emit (#1056)

    func testEnumTypeNameForKeywordNamedField() throws {
        // #1056: an `enum` on a Swift-keyword-named field (`default`) must
        // produce a legal nested *type* name. A type name can't be
        // backtick-escaped, so the emitter sanitizes: `default` →
        // `DefaultValue` (the `Value` suffix also lifts it out of
        // keyword-space). The accessor name is `defaultEnum`; the stored
        // property ref inside it stays backtick-escaped (`` `default` ``).
        let src = try emit("""
        [models.widget]
        [models.widget.fields.id]
        type = "id"
        [models.widget.fields.default]
        type = "string"
        enum = ["on", "off"]
        """)
        let body = try XCTUnwrap(src["WidgetRecord"])
        XCTAssertTrue(body.contains("enum DefaultValue: String, Codable, CaseIterable, Sendable"),
                      "keyword field should yield a sanitized type name `DefaultValue`:\n\(body)")
        XCTAssertTrue(body.contains("var defaultEnum: DefaultValue?"))
        XCTAssertFalse(body.contains("`default`Value"),
                       "must not backtick-wrap the keyword inside a type name")
        XCTAssertFalse(body.contains("`default`Enum"),
                       "must not backtick-wrap only the keyword in the accessor name")
        // Cases preserve raw values verbatim.
        XCTAssertTrue(body.contains(#"case on = "on""#))
        XCTAssertTrue(body.contains(#"case off = "off""#))
    }

    func testEnumTypeNameDerivationSanitizes() throws {
        // Unit-test the type-name derivation directly: a keyword field lands
        // out of keyword-space via the `Value` suffix; a leading-digit name
        // is `_`-prefixed; punctuation/Unicode-digit chars are stripped — all
        // so the emitted nested `enum <Name>:` is a legal type identifier
        // that can't be expressed by backtick-escaping. (Driving these
        // through full `emit()` isn't possible in isolation because the same
        // field names also need to be legal *property* identifiers, a
        // separate emitter concern — so we pin the derivation here.)
        XCTAssertEqual(Naming.enumTypeName(forField: "default"), "DefaultValue")
        XCTAssertEqual(Naming.enumTypeName(forField: "user_status"), "UserStatusValue")
        XCTAssertEqual(Naming.enumTypeName(forField: "2fa"), "_2faValue")
        XCTAssertEqual(Naming.enumTypeName(forField: "order.status"), "OrderstatusValue")
        XCTAssertEqual(Naming.enumTypeName(forField: "Self"), "SelfValue")
        // Empty / all-punctuation degrades to a lone `_` base.
        XCTAssertEqual(Naming.enumTypeName(forField: "."), "_Value")
    }

    func testEnumAndAutoStampCompose() throws {
        // Both emit paths on one model — enum on a normal field plus an
        // auto_stamp field — to pin that they don't interfere.
        let src = try emit("""
        [models.task]
        [models.task.fields.id]
        type = "id"
        [models.task.fields.status]
        type = "string"
        enum = ["todo", "done"]
        [models.task.fields.createdAt]
        type = "number"
        auto_stamp = "create"
        """)
        let body = try XCTUnwrap(src["TaskRecord"])
        XCTAssertTrue(body.contains("enum StatusValue: String"))
        XCTAssertTrue(body.contains("var statusEnum: StatusValue?"))
        XCTAssertTrue(body.contains("FieldDescriptor(type: .number, autoStamp: .create)"))
        XCTAssertTrue(body.contains("static let autoStampFields: [String: String]"))
    }
}
