import XCTest
@testable import SwiftBaoCodegen

final class SwiftEmitterTests: XCTestCase {

    private func emit(_ toml: String, opts: EmitOptions = EmitOptions()) throws -> [String: String] {
        let schemas = try TomlParser.parse(tomlString: toml, swiftNameSuffix: "Record")
        let emitter = SwiftEmitter(options: opts)
        var out: [String: String] = [:]
        for s in schemas {
            out[s.swiftName] = emitter.emit(schema: s)
        }
        return out
    }

    func testGeneratedStructConformsToEquatableHashableCodable() throws {
        // A2 — codegen emits `Equatable, Hashable, Codable` on the
        // struct itself so the compiler's same-file synthesis fires.
        // This obsoletes the ~80 lines of hand-rolled boilerplate
        // users used to need per model. Pin the contract.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(
            body.contains("struct TRecord: PrimitiveModel, Equatable, Hashable, Codable"),
            "generated struct should conform to PrimitiveModel + Equatable, Hashable, Codable so synthesis fires"
        )
    }

    func testEmitsHeader() throws {
        let src = try emit("[models.x]\n[models.x.fields.id]\ntype = \"id\"")
        let body = try XCTUnwrap(src["XRecord"])
        XCTAssertTrue(body.contains("// Generated by swift-bao-codegen — DO NOT EDIT."))
        XCTAssertTrue(body.contains("import JsBaoClient"))
    }

    func testCustomModuleImport() throws {
        let opts = EmitOptions(accessLevel: "internal", moduleImport: "MyCore", sourcePath: "schema.toml")
        let src = try emit("[models.x]\n[models.x.fields.id]\ntype = \"id\"", opts: opts)
        XCTAssertTrue(try XCTUnwrap(src["XRecord"]).contains("import MyCore"))
    }

    func testPublicAccessPropagatesEverywhere() throws {
        let opts = EmitOptions(accessLevel: "public", moduleImport: "JsBaoClient", sourcePath: "")
        let src = try emit("""
        [models.tasks]
        [models.tasks.fields.id]
        type = "id"
        [models.tasks.fields.title]
        type = "string"
        required = true
        """, opts: opts)
        let body = try XCTUnwrap(src["TasksRecord"])
        XCTAssertTrue(body.contains("public struct TasksRecord"))
        XCTAssertTrue(body.contains("public static let modelName"))
        XCTAssertTrue(body.contains("public var id: String"))
        XCTAssertTrue(body.contains("public init?(record:"))
        XCTAssertTrue(body.contains("public func primitiveValues"))
    }

    func testDefaultAccessIsPublic() throws {
        // The default access modifier emitted by codegen must be
        // `public` — app code typically adds a companion extension
        // (`public extension TodoItem { init(text: String) { ... } }`),
        // which the compiler rejects on internal types ("public
        // modifier cannot be used in extensions that declare members
        // on an internal type"). Pin the default so future refactors
        // can't silently regress.
        let src = try emit("""
        [models.tasks]
        [models.tasks.fields.id]
        type = "id"
        """)
        let body = try XCTUnwrap(src["TasksRecord"])
        XCTAssertTrue(body.contains("public struct TasksRecord"),
                      "default emitter access should be `public`")
        XCTAssertTrue(body.contains("public var id: String"))
        XCTAssertTrue(body.contains("public init("))
    }

    func testPrimitiveValuesUsesLetWhenNoOptionalFields() throws {
        // No optional fields → `values` is never mutated, so the
        // emitter must use `let` to avoid the per-build
        // "variable 'values' was never mutated" warning.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("let values: [String: PrimitiveValue] = ["),
                      "expected `let values` when no optional fields are present")
        XCTAssertFalse(body.contains("var values: [String: PrimitiveValue]"),
                       "should not emit `var values` when nothing mutates it")
    }

    func testPrimitiveValuesUsesVarWhenOptionalFieldsPresent() throws {
        // Optional fields → `values` is conditionally extended via
        // `values["x"] = ...`, so `var` is required.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        [models.t.fields.note]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var values: [String: PrimitiveValue]"),
                      "expected `var values` when there's at least one optional field")
    }

    func testBooleanRowReadUsesNonTrailingClosure() throws {
        // `(row[..] as? Int).map { ... }` triggers the "trailing
        // closure in this context is confusable with the body of the
        // statement" warning when it sits inside a `guard let ... else
        // { return nil }` chain. The emitter must use the
        // non-trailing form `.map({ ... })`.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.done]
        type = "boolean"
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains(".map({ $0 != 0 })"),
                      "boolean row-read should use non-trailing closure")
        XCTAssertFalse(body.contains(".map { $0 != 0 }"),
                       "no trailing-closure form for boolean row-read")
    }

    func testInitParameterOrderMatchesSchemaDeclarationOrder() throws {
        // The parser recovers field declaration order from the TOML
        // source — a schema written `zzz, id, aaa` emits an init in
        // that *same* order, not alphabetical (which would silently
        // re-shuffle a caller's positional args). The runtime never
        // depends on init parameter order, so source-order is purely
        // a developer-ergonomics fix.
        let src = try emit("""
        [models.tasks]
        [models.tasks.fields.zzz]
        type = "string"
        [models.tasks.fields.id]
        type = "id"
        [models.tasks.fields.aaa]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TasksRecord"])
        guard let initRange = body.range(of: "init(\n") else {
            return XCTFail("no init found")
        }
        let initBody = body[initRange.upperBound...]
        let paramLines = initBody.split(separator: "\n").prefix(3).map(String.init)
        XCTAssertTrue(paramLines[0].contains("zzz:"),
                      "expected zzz first, got: \(paramLines[0])")
        XCTAssertTrue(paramLines[1].contains("id:"),
                      "expected id second, got: \(paramLines[1])")
        XCTAssertTrue(paramLines[2].contains("aaa:"),
                      "expected aaa third, got: \(paramLines[2])")
    }

    func testRequiredFieldGuardsInRecordInit() throws {
        let src = try emit("""
        [models.tasks]
        [models.tasks.fields.id]
        type = "id"
        [models.tasks.fields.title]
        type = "string"
        required = true
        [models.tasks.fields.note]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TasksRecord"])
        XCTAssertTrue(body.contains(#"guard let title = record["title"]?.asString"#))
        // Optional `note` should NOT be in the guard.
        XCTAssertFalse(body.contains(#"let note = record["note"]"#))
        XCTAssertTrue(body.contains(#"self.note = record["note"]?.asString"#))
    }

    func testAllOptionalFieldsOmitsGuardInRecordInit() throws {
        let src = try emit("""
        [models.x]
        [models.x.fields.id]
        type = "id"
        [models.x.fields.counter]
        type = "number"
        """)
        let body = try XCTUnwrap(src["XRecord"])
        // Locate just the record-init body. init?(row:) always guards
        // on `id` from the row dict, so we can't check the whole file.
        guard let recordInitStart = body.range(of: "init?(record: PrimitiveRecord)") else {
            return XCTFail("no record init found")
        }
        guard let rowInitStart = body.range(of: "init?(row:") else {
            return XCTFail("no row init found")
        }
        let recordInitBody = body[recordInitStart.upperBound..<rowInitStart.lowerBound]
        XCTAssertFalse(
            recordInitBody.contains("guard"),
            "init?(record:) should not have a guard when no fields are required:\n\(recordInitBody)"
        )
    }

    func testFieldTypeMappings() throws {
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.s]
        type = "string"
        [models.t.fields.n]
        type = "number"
        [models.t.fields.b]
        type = "boolean"
        [models.t.fields.d]
        type = "date"
        [models.t.fields.tags]
        type = "stringset"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var s: String?"))
        XCTAssertTrue(body.contains("var n: Double?"))
        XCTAssertTrue(body.contains("var b: Bool?"))
        XCTAssertTrue(body.contains("var d: String?"))
        XCTAssertTrue(body.contains("var tags: Set<String>?"))
        // accessors
        XCTAssertTrue(body.contains(".asString"))
        XCTAssertTrue(body.contains(".asNumber"))
        XCTAssertTrue(body.contains(".asBoolean"))
        XCTAssertTrue(body.contains(".asDateString"))
        XCTAssertTrue(body.contains(".asStringSet"))
    }

    func testRequiredFieldIsNonOptional() throws {
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var title: String\n"))
    }

    func testPrimitiveValuesShape() throws {
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.title]
        type = "string"
        required = true
        [models.t.fields.note]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        // Required goes in the literal; optional uses `if let`.
        XCTAssertTrue(body.contains(#""title": .string(title)"#))
        XCTAssertTrue(body.contains(#"if let note { values["note"] = .string(note) }"#))
    }

    func testFieldDescriptorIncludesRelevantFlags() throws {
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.email]
        type = "string"
        unique = true
        indexed = true
        max_length = 256
        required = true
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(
            body.contains(#"FieldDescriptor(type: .string, indexed: true, unique: true, required: true, maxLength: 256)"#),
            body
        )
    }

    func testCustomClassNameOverride() throws {
        let src = try emit("""
        [models.tasks]
        class_name = "TaskRecord"

        [models.tasks.fields.id]
        type = "id"
        """)
        XCTAssertNotNil(src["TaskRecord"])
        XCTAssertNil(src["TasksRecord"])
    }

    func testSwiftKeywordFieldNameIsBacktickEscaped() throws {
        // Swift's `default` is a keyword — emitter must wrap in backticks.
        // This isn't user-friendly, but the alternative (silently renaming)
        // breaks the model name → field key invariant the runtime relies on.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields.default]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var `default`: String?"))
    }

    func testEverySwiftKeywordAsFieldName_isBacktickEscapedEverywhere() throws {
        // Sweep every reserved keyword the emitter knows about and
        // verify the generated code escapes it at every Swift-identifier
        // call site:
        //   1. The stored property declaration
        //   2. The designated init parameter
        //   3. The designated init body LHS + RHS
        //   4. The init?(record:) body LHS
        //   5. The init?(row:) body LHS
        //   6. The primitiveValues() body (`if let` shorthand + .string(...) ref)
        //
        // A few keywords would either not parse as a TOML key without
        // quoting (e.g. one with whitespace) or are already exercised
        // elsewhere — skip those. This loop catches the long tail.
        // The wider point is: the emitter routes every field-name use
        // through `propName(...)`; if a future refactor ever bypasses
        // it, this test fails loud across the whole keyword set.
        for keyword in [
            "class", "init", "var", "let", "for", "while", "if", "else",
            "return", "break", "continue", "throw", "try", "catch",
            "switch", "case", "where", "guard", "defer", "do", "in",
            "self", "Self", "Any", "true", "false", "nil", "default",
            "static", "func", "private", "public", "internal", "open",
            "operator", "subscript", "typealias", "rethrows", "throws",
            "protocol", "extension", "struct", "enum", "import",
        ] {
            let toml = """
            [models.t]
            [models.t.fields.id]
            type = "id"
            [models.t.fields.\(keyword)]
            type = "string"
            """
            let src = try emit(toml)
            let body = try XCTUnwrap(src["TRecord"], "no TRecord for keyword '\(keyword)'")

            // Stored property declaration
            XCTAssertTrue(
                body.contains("var `\(keyword)`: String?"),
                "missing stored property backtick escape for '\(keyword)'"
            )
            // Designated init body — `self.\`X\` = \`X\``
            XCTAssertTrue(
                body.contains("self.`\(keyword)` = `\(keyword)`"),
                "missing designated-init body escape for '\(keyword)'"
            )
            // init?(record:) body
            XCTAssertTrue(
                body.contains("self.`\(keyword)` = record[\"\(keyword)\"]?"),
                "missing init?(record:) body escape for '\(keyword)'"
            )
            // init?(row:) body
            XCTAssertTrue(
                body.contains("self.`\(keyword)` = row[\"\(keyword)\"]"),
                "missing init?(row:) body escape for '\(keyword)'"
            )
            // primitiveValues() body — `if let \`X\` { values["X"] = .string(\`X\`) }`
            XCTAssertTrue(
                body.contains("if let `\(keyword)`"),
                "missing primitiveValues() if-let escape for '\(keyword)'"
            )
            XCTAssertTrue(
                body.contains(".string(`\(keyword)`)"),
                "missing primitiveValues() value-ref escape for '\(keyword)'"
            )
        }
    }

    func testFieldNameStartingWithUnderscore_isPreservedAsIs() throws {
        // Field names starting with `_` are RESERVED in convention
        // (`_meta_*`, `_uniqueIdx_*`, `_meta_doc_id`) but the emitter
        // doesn't currently reject them — it just emits them. Test
        // pins that today behavior; if we ever add validation, this
        // should flip to expect a thrown CodegenError.
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields._user_meta]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var _user_meta: String?"),
                      "underscore-prefixed field names are emitted as-is today")
    }

    func testUnicodeFieldName_requiresQuotedTomlKey_andEmitsAsIs() throws {
        // TOML spec: bare keys are ASCII `[A-Za-z0-9_-]+` only.
        // Non-ASCII keys MUST be quoted (`"café"`). With quoted keys
        // the field passes through the emitter untouched and lands
        // on the generated struct as a Swift identifier (Swift
        // accepts Unicode L*/Nl chars in identifiers).
        let src = try emit("""
        [models.t]
        [models.t.fields.id]
        type = "id"
        [models.t.fields."café"]
        type = "string"
        """)
        let body = try XCTUnwrap(src["TRecord"])
        XCTAssertTrue(body.contains("var café: String?"),
                      "unicode field name should emit as-is when TOML key is quoted")
    }

    func testUnicodeModelName_requiresQuotedTomlKey_emitsPascalCased() throws {
        // Same TOML rule — model names with non-ASCII must be quoted
        // in the table header. `Naming.pascalCase` only special-cases
        // `_`/`-`/space as word boundaries, so a unicode model name
        // surfaces with its first character upper-cased and the rest
        // verbatim. Default suffix `Record` appended.
        let src = try emit("""
        [models."café"]
        [models."café".fields.id]
        type = "id"
        """)
        XCTAssertNotNil(src["CaféRecord"],
                        "expected CaféRecord, got keys: \(Array(src.keys))")
    }

    func testUnquotedUnicodeKey_doesNotEmitAModel() throws {
        // TOML spec rejects unquoted non-ASCII bare keys. Two valid
        // outcomes here:
        //   • TOMLKit raises a parse error → `.parse` is thrown.
        //   • TOMLKit truncates `[models.café]` to a bare `[models]`
        //     header with no children → we successfully parse an empty
        //     schema list (since a comment-only / model-less TOML is
        //     valid input for fresh-template onboarding).
        // The user-visible failure mode in the second case is "my
        // generated type is missing", which they'll hit immediately at
        // compile time — quoting the key fixes it.
        do {
            let src = try emit("""
            [models.café]
            [models.café.fields.id]
            type = "id"
            """)
            XCTAssertTrue(src.isEmpty,
                          "expected zero emitted records, got keys: \(Array(src.keys))")
        } catch CodegenError.parse {
            // Acceptable: TOMLKit surfaced a parse error.
        } catch {
            XCTFail("expected CodegenError.parse or empty output, got \(error)")
        }
    }
}
