import Foundation
@testable import JsBaoClient

// Hand-written helpers exercising the recommended pattern for adding
// behavior on top of codegen-emitted structs: free functions, NOT
// extensions on the generated type.
//
// Lives next to (not inside) Generated/ so the codegen tool's sweep
// — which deletes only files starting with the `// Generated by
// swift-bao-codegen` banner — can never touch it. This file
// intentionally has no banner; the gauntlet pins that contract.
//
// Why free functions over extensions on the generated type? Match the
// TS codegen, which doesn't reach into the generated `Contact` class
// either. Helpers as free functions stay clearly user code, don't
// grow the generated type's namespace with surprises across files,
// and can't accidentally collide with codegen output on a future
// emitter change. See docs/codegen.md → "Adding helpers (free
// functions)".

// "Computed display value" pattern — uppercase the optional name with
// id fallback. Reads codegen-emitted optionals and the always-present
// id; matches what users typically write when they want a derived
// label alongside the codegen output.
func displayTitle(_ record: CrashTestRecord) -> String {
    record.boundedName?.uppercased() ?? "(\(record.id))"
}

// Factory-style helper. Funnels into the codegen designated init.
// Equivalent to a "convenience init" in Swift, but written as a free
// function so it's clearly user code and doesn't extend the
// generated struct's API.
func placeholderCrashTestRecord(named name: String) -> CrashTestRecord {
    CrashTestRecord(
        id: "placeholder-\(name)",
        boundedName: name,
        requiredTags: ["placeholder"]
    )
}

// Generic free function over PrimitiveModel. Compiles against any
// codegen-emitted struct exactly because the protocol's static and
// instance requirements are what codegen emits. Useful for "describe
// any record" helpers in inspectors and test gauntlets.
func describeAnyPrimitive<M: PrimitiveModel>(_ value: M) -> String {
    "\(M.modelName)#\(value.id)"
}
