import Foundation

struct EmitOptions {
    /// Access level applied to the generated struct, its members, and
    /// init signatures. Default is `public` so that app code can write
    /// `public extension TodoItem { ... }` (the shape the agent guide
    /// shows) without hitting the "public modifier cannot be used in
    /// extensions that declare members on an internal type" diagnostic.
    /// Override to `"internal"` for embedded-in-module use.
    var accessLevel: String = "public"

    /// The module that exports `PrimitiveModel`, `PrimitiveSchema`,
    /// `PrimitiveValue`, etc. Almost always `JsBaoClient`.
    var moduleImport: String = "JsBaoClient"

    /// Source file path written into the generated header comment so
    /// readers can find the TOML quickly. Pass an empty string to omit.
    var sourcePath: String = "schema.toml"
}

/// Emit one Swift source file per `ParsedSchema`. The generator never
/// loads or executes Swift — it's a string-template pass — so the build
/// tool plugin doesn't need a Swift toolchain beyond what's already
/// running the compile step.
struct SwiftEmitter {
    let options: EmitOptions

    init(options: EmitOptions) {
        self.options = options
    }

    func emit(schema: ParsedSchema) -> String {
        var src = ""
        src += header(schema: schema)
        src += "import Foundation\n"
        src += "import \(options.moduleImport)\n\n"
        src += structDecl(schema: schema)
        return src
    }

    // MARK: - Header

    private func header(schema: ParsedSchema) -> String {
        var s = "// Generated by swift-bao-codegen — DO NOT EDIT.\n"
        if !options.sourcePath.isEmpty {
            s += "// Source: \(options.sourcePath) (model: \(schema.name))\n"
        } else {
            s += "// Model: \(schema.name)\n"
        }
        s += "\n"
        return s
    }

    // MARK: - Struct

    /// Emit-time field order. `TomlParser` already recovers TOML
    /// declaration order from the source, so the emitter just preserves
    /// it — a schema declared as `id, text, completed, createdAt` yields
    /// an init in that exact parameter order. (Previously this pinned
    /// `id` to the front because TOMLKit's iteration is alphabetical;
    /// the source-order recovery makes that hack unnecessary.)
    private func displayFieldOrder(_ schema: ParsedSchema) -> [String] {
        return schema.fieldOrder
    }

    private func structDecl(schema: ParsedSchema) -> String {
        let access = options.accessLevel
        let typeName = schema.swiftName
        // `Equatable`, `Hashable`, and `Codable` synthesis only fires
        // when the conformance lives in the SAME file as the type
        // declaration. Adding the conformances here lets callers get
        // them for free — saves ~80 lines of hand-rolled boilerplate
        // per model. All generated stored-property types conform
        // (`String`, `Double`, `Bool`, `Set<String>`, plus their
        // optional forms), so synthesis succeeds for every schema.
        // CodingKeys synthesis also handles backtick-escaped property
        // names automatically (Swift 5.1+), so reserved-keyword
        // fields like `default` / `where` round-trip through
        // `JSONEncoder` / `JSONDecoder` without needing a manual
        // `CodingKeys` enum.
        var out = "\(access) struct \(typeName): PrimitiveModel, Equatable, Hashable, Codable {\n"
        out += staticMembers(schema: schema)
        out += "\n"
        out += storedProperties(schema: schema)
        out += "\n"
        out += designatedInit(schema: schema)
        out += "\n"
        out += recordInit(schema: schema)
        out += "\n"
        out += rowInit(schema: schema)
        out += "\n"
        out += primitiveValuesFn(schema: schema)
        out += "}\n"
        return out
    }

    private func staticMembers(schema: ParsedSchema) -> String {
        let access = options.accessLevel
        var out = "    \(access) static let modelName = \(quoted(schema.name))\n"
        out += "    \(access) static let primitiveSchema = PrimitiveSchema(\n"
        out += "        name: \(quoted(schema.name)),\n"
        out += "        fields: [\n"
        // Preserve TOML insertion order for determinism, but collect the
        // longest key length for column-aligned readability.
        let keyWidth = displayFieldOrder(schema).map { $0.count + 2 }.max() ?? 0
        for fname in displayFieldOrder(schema) {
            guard let field = schema.fields[fname] else { continue }
            let key = quoted(fname)
            let pad = String(repeating: " ", count: max(0, keyWidth - key.count))
            out += "            \(key):\(pad) \(fieldDescriptorLiteral(field)),\n"
        }
        out += "        ]"
        if !schema.uniqueConstraints.isEmpty {
            out += ",\n        constraints: [\n"
            for c in schema.uniqueConstraints {
                let fieldsLit = c.fields.map { quoted($0) }.joined(separator: ", ")
                out += "            \(quoted(c.name)): ConstraintDescriptor(name: \(quoted(c.name)), fields: [\(fieldsLit)]),\n"
            }
            out += "        ]"
        }
        if !schema.relationships.isEmpty {
            out += ",\n        relationships: [\n"
            for (rname, rel) in schema.relationships {
                let propsLit = rel.properties.map { "\(quoted($0.0)): \(quoted($0.1))" }.joined(separator: ", ")
                out += "            \(quoted(rname)): RelationshipDescriptor(properties: [\(propsLit)]),\n"
            }
            out += "        ]"
        }
        out += "\n    )\n"
        return out
    }

    private func fieldDescriptorLiteral(_ f: ParsedField) -> String {
        var args: [String] = ["type: \(swiftFieldType(f.type))"]
        if f.indexed    { args.append("indexed: true") }
        if f.unique     { args.append("unique: true") }
        if f.required   { args.append("required: true") }
        if f.autoAssign { args.append("autoAssign: true") }
        if let v = f.maxLength { args.append("maxLength: \(v)") }
        if let v = f.maxCount  { args.append("maxCount: \(v)") }
        if let d = f.defaultLiteral {
            args.append("default: \(defaultLiteral(d))")
        }
        return "FieldDescriptor(\(args.joined(separator: ", ")))"
    }

    private func swiftFieldType(_ t: ParsedFieldType) -> String {
        switch t {
        case .string:    return ".string"
        case .number:    return ".number"
        case .boolean:   return ".boolean"
        case .date:      return ".date"
        case .id:        return ".id"
        case .stringset: return ".stringset"
        }
    }

    private func defaultLiteral(_ d: ParsedDefault) -> String {
        switch d {
        case let .string(s):
            return ".scalar(.string(\(quoted(s))))"
        case let .number(n):
            return ".scalar(.number(\(formatDouble(n))))"
        case let .integer(i):
            return ".scalar(.number(\(i)))"
        case let .boolean(b):
            return ".scalar(.boolean(\(b)))"
        }
    }

    // MARK: - Stored properties

    private func storedProperties(schema: ParsedSchema) -> String {
        let access = options.accessLevel
        var out = ""
        for fname in displayFieldOrder(schema) {
            guard let f = schema.fields[fname] else { continue }
            out += "    \(access) var \(propName(fname)): \(swiftStoredType(f, fieldName: fname))\n"
        }
        return out
    }

    /// Map a TOML field type to the user-facing Swift type. `id` and
    /// any `required: true` field is non-optional; everything else is
    /// optional. `id` always becomes `String` (PrimitiveRecord exposes
    /// it as `record.id`).
    private func swiftStoredType(_ f: ParsedField, fieldName: String) -> String {
        let base: String
        switch f.type {
        case .string, .id, .date: base = "String"
        case .number:              base = "Double"
        case .boolean:             base = "Bool"
        case .stringset:           base = "Set<String>"
        }
        let nonOptional = (f.type == .id) || f.required || (fieldName == "id")
        return nonOptional ? base : "\(base)?"
    }

    // MARK: - Designated init

    private func designatedInit(schema: ParsedSchema) -> String {
        let access = options.accessLevel
        var lines: [String] = []
        for fname in displayFieldOrder(schema) {
            guard let f = schema.fields[fname] else { continue }
            let type = swiftStoredType(f, fieldName: fname)
            let isOptional = type.hasSuffix("?")
            // No defaults for non-optional `id` (caller must provide one).
            // Required non-id fields also have no default — matches the
            // demo's hand-written init shape.
            let suffix: String
            if isOptional {
                suffix = " = nil"
            } else {
                suffix = ""
            }
            lines.append("        \(propName(fname)): \(type)\(suffix)")
        }
        var out = "    \(access) init(\n"
        out += lines.joined(separator: ",\n")
        out += "\n    ) {\n"
        for fname in displayFieldOrder(schema) {
            out += "        self.\(propName(fname)) = \(propName(fname))\n"
        }
        out += "    }\n"
        return out
    }

    // MARK: - init?(record:)

    private func recordInit(schema: ParsedSchema) -> String {
        let access = options.accessLevel
        var out = "    \(access) init?(record: PrimitiveRecord) {\n"

        // Required guards for non-`id` required fields (id comes from
        // record.id and is always present).
        var guards: [String] = []
        for fname in displayFieldOrder(schema) {
            guard let f = schema.fields[fname] else { continue }
            if fname == "id" { continue }
            if f.required {
                guards.append(
                    "let \(propName(fname)) = record[\(quoted(fname))]?.\(asAccessor(f.type))"
                )
            }
        }
        if !guards.isEmpty {
            out += "        guard "
            out += guards.joined(separator: ",\n              ")
            out += "\n        else { return nil }\n"
        }
        // Assignments
        for fname in displayFieldOrder(schema) {
            guard let f = schema.fields[fname] else { continue }
            if fname == "id" {
                out += "        self.id = record.id\n"
                continue
            }
            if f.required {
                // Hoisted from the guard
                out += "        self.\(propName(fname)) = \(propName(fname))\n"
            } else {
                let acc = asAccessor(f.type)
                out += "        self.\(propName(fname)) = record[\(quoted(fname))]?.\(acc)\n"
            }
        }
        out += "    }\n"
        return out
    }

    /// The right `asXxx` PrimitiveValue accessor for a field type.
    /// `.date` reads as a `String` — the demo and the runtime use ISO-8601
    /// strings so dates don't need a separate Swift type. `.stringset`
    /// reads as `Set<String>?`.
    private func asAccessor(_ t: ParsedFieldType) -> String {
        switch t {
        case .string:    return "asString"
        case .number:    return "asNumber"
        case .boolean:   return "asBoolean"
        case .id:        return "asId"
        case .date:      return "asDateString"
        case .stringset: return "asStringSet"
        }
    }

    // MARK: - init?(row:)

    private func rowInit(schema: ParsedSchema) -> String {
        let access = options.accessLevel
        var out = "    /// Build from a SQLite-backed query row (`dynamic.query(...)`).\n"
        out += "    \(access) init?(row: [String: Any]) {\n"
        // Always require id from the row.
        var guardClauses: [String] = ["let id = row[\"id\"] as? String"]
        for fname in displayFieldOrder(schema) {
            guard let f = schema.fields[fname] else { continue }
            if fname == "id" { continue }
            if f.required {
                guardClauses.append(
                    "let \(propName(fname)) = \(rowReadExpression(f, key: quoted(fname)))"
                )
            }
        }
        out += "        guard "
        out += guardClauses.joined(separator: ",\n              ")
        out += "\n        else { return nil }\n"
        out += "        self.id = id\n"
        for fname in displayFieldOrder(schema) {
            guard let f = schema.fields[fname] else { continue }
            if fname == "id" { continue }
            if f.required {
                out += "        self.\(propName(fname)) = \(propName(fname))\n"
            } else {
                out += "        self.\(propName(fname)) = \(rowReadExpression(f, key: quoted(fname)))\n"
            }
        }
        out += "    }\n"
        return out
    }

    /// The expression that reads one field out of a SQLite-row dict.
    ///
    /// Scalars (`string` / `number` / `boolean` / `id` / `date`) are
    /// straight `as?` casts to their Swift type. Stringsets are special:
    /// `BaoModelQueryEngine.populateStringsetsFiltered` writes stringset
    /// columns back into the row dict as `[String]` (Swift array), not
    /// as `Set<String>`, so a direct `as? Set<String>` cast always
    /// fails and the row is silently dropped. Cast to `[String]` first
    /// and convert.
    ///
    /// The expression returns an `Optional` of the field's storage
    /// type — caller wraps in `let prop = ...` to unwrap it.
    private func rowReadExpression(_ f: ParsedField, key: String) -> String {
        if f.type == .stringset {
            return "(row[\(key)] as? [String]).map(Set.init)"
        }
        if f.type == .boolean {
            // BaoModelQueryEngine.executeQuery returns SQLite INTEGER
            // columns as `Int` — boolean fields are stored as INTEGER,
            // so a direct `as? Bool` cast always fails and the row's
            // bool either drops silently (optional) or aborts the
            // whole row (required). Fall back through Int → Bool.
            //
            // Use a non-trailing closure on `.map` because the read
            // expression sits inside a `guard let X = ..., let Y = ...
            // else { return nil }` chain — a trailing closure there
            // triggers the "trailing closure in this context is
            // confusable with the body of the statement" warning.
            return "(row[\(key)] as? Bool) ?? (row[\(key)] as? Int).map({ $0 != 0 })"
        }
        return "row[\(key)] as? \(swiftRowCastType(f))"
    }

    /// The non-optional Swift type for a SQLite row-cast (`as? T`).
    /// `.stringset` does not appear here — `rowReadExpression` handles
    /// it via the `[String] → Set<String>` conversion path.
    private func swiftRowCastType(_ f: ParsedField) -> String {
        switch f.type {
        case .string, .id, .date: return "String"
        case .number:              return "Double"
        case .boolean:             return "Bool"
        case .stringset:           return "Set<String>"   // unused; handled in rowReadExpression
        }
    }

    // MARK: - primitiveValues()

    private func primitiveValuesFn(schema: ParsedSchema) -> String {
        let access = options.accessLevel
        var out = "    \(access) func primitiveValues() -> [String: PrimitiveValue] {\n"

        // Required fields go in the literal; optional fields are
        // appended conditionally. `id` is excluded — DynamicModel writes
        // it separately.
        var requiredEntries: [(String, ParsedField)] = []
        var optionalEntries: [(String, ParsedField)] = []
        for fname in displayFieldOrder(schema) {
            guard let f = schema.fields[fname] else { continue }
            if fname == "id" { continue }
            if f.required {
                requiredEntries.append((fname, f))
            } else {
                optionalEntries.append((fname, f))
            }
        }

        // `values` is mutated only when there are optional fields to
        // conditionally append — emit `let` otherwise to avoid the
        // "variable 'values' was never mutated" warning in app builds.
        let storageKeyword = optionalEntries.isEmpty ? "let" : "var"
        if requiredEntries.isEmpty {
            out += "        \(storageKeyword) values: [String: PrimitiveValue] = [:]\n"
        } else {
            out += "        \(storageKeyword) values: [String: PrimitiveValue] = [\n"
            for (fname, f) in requiredEntries {
                out += "            \(quoted(fname)): \(primitiveValueLiteral(f, propRef: propName(fname))),\n"
            }
            out += "        ]\n"
        }
        for (fname, f) in optionalEntries {
            // String?, Double?, Bool?, Set<String>? — `if let` shorthand
            out += "        if let \(propName(fname)) { values[\(quoted(fname))] = \(primitiveValueLiteral(f, propRef: propName(fname))) }\n"
        }
        out += "        return values\n"
        out += "    }\n"
        return out
    }

    private func primitiveValueLiteral(_ f: ParsedField, propRef: String) -> String {
        switch f.type {
        case .string:    return ".string(\(propRef))"
        case .number:    return ".number(\(propRef))"
        case .boolean:   return ".boolean(\(propRef))"
        case .id:        return ".id(\(propRef))"
        case .date:      return ".date(\(propRef))"
        case .stringset: return ".stringset(\(propRef))"
        }
    }

    // MARK: - Helpers

    private func propName(_ s: String) -> String {
        Naming.escapeIfReserved(s)
    }

    private func quoted(_ s: String) -> String {
        // Conservative: the field/model names that survive TOML parsing
        // can't contain `"` or `\`, so a verbatim wrap is safe.
        return "\"\(s)\""
    }

    private func formatDouble(_ d: Double) -> String {
        if d.isFinite, d == d.rounded(), abs(d) < 1e16 {
            return "\(Int64(d))"
        }
        return "\(d)"
    }
}
